apiVersion: apps/v1
kind: Deployment
metadata:
  name: yjdeploymentb
  labels:
    app: yj-serviceb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: yj-serviceb
  strategy: {}
  template:
    metadata:
      labels:
        app: yj-serviceb
    spec:
      containers:
      - image: rnjsxorl3075/serviceb:7
        name: yj-serviceb
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
