apiVersion: apps/v1
kind: Deployment
metadata:
  name: yjdeployment
  labels:
    app: yj-servicea
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: yj-servicea
  strategy: {}
  template:
    metadata:
      labels:
        app: yj-servicea
    spec:
      containers:
      - image: rnjsxorl3075/servicea:33
        name: yj-servicea
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
